name: blogapp

services:
  db:
    image: postgres:latest
    container_name: blog_db
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1440
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - blog_network

  blog_app:
    build:
      context: ./blog_backend
      dockerfile: Dockerfile
#    image: imbeer/blog-blog_app:latest
    container_name: drogon_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - blog_network
    volumes:
      - uploads:/app/blog_backend/build/uploads # images dir
      - ./local_config:/app/blog_backend/local_config # config.json dir
    environment:
      - IMAGE_DIR=/app/blog_backend/build/uploads

volumes:
  db_data:
    driver: local
  uploads:
    driver: local

networks:
  blog_network:
    driver: bridge

